<?php

use Illuminate\Database\Seeder;

class SaleInvoiceItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sale_invoice_items')->delete();
        
        \DB::table('sale_invoice_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'sale_invoice_id' => 1,
                'product_id' => 3,
                'quantity' => 1,
                'neto_import' => 200.0,
                'iva_import' => 42.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 242.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 14:21:46',
                'updated_at' => '2020-08-01 14:21:46',
            ),
            1 => 
            array (
                'id' => 2,
                'sale_invoice_id' => 2,
                'product_id' => 10,
                'quantity' => 1,
                'neto_import' => 900.0,
                'iva_import' => 189.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 1089.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 14:36:12',
                'updated_at' => '2020-08-01 14:36:12',
            ),
            2 => 
            array (
                'id' => 3,
                'sale_invoice_id' => 3,
                'product_id' => 54,
                'quantity' => 1,
                'neto_import' => 5300.0,
                'iva_import' => 1113.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 6413.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 16:16:36',
                'updated_at' => '2020-08-01 16:16:36',
            ),
            3 => 
            array (
                'id' => 4,
                'sale_invoice_id' => 4,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 366.94,
                'iva_import' => 77.06,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 444.0,
                'obs' => 'ggggggggggggg',
                'created_at' => '2020-08-01 16:22:06',
                'updated_at' => '2020-08-01 16:22:06',
            ),
            4 => 
            array (
                'id' => 5,
                'sale_invoice_id' => 5,
                'product_id' => 7,
                'quantity' => 1,
                'neto_import' => 555.0,
                'iva_import' => 116.55,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 67155.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 18:18:06',
                'updated_at' => '2020-08-01 18:18:06',
            ),
            5 => 
            array (
                'id' => 6,
                'sale_invoice_id' => 6,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 100.0,
                'iva_import' => 21.0,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 121.0,
                'obs' => 'sssss sssss ssss',
                'created_at' => '2020-08-01 18:19:37',
                'updated_at' => '2020-08-01 18:19:37',
            ),
            6 => 
            array (
                'id' => 7,
                'sale_invoice_id' => 6,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 458.68,
                'iva_import' => 96.32,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 555.0,
                'obs' => 'uuuuuuuuuuu8',
                'created_at' => '2020-08-01 18:19:37',
                'updated_at' => '2020-08-01 18:19:37',
            ),
            7 => 
            array (
                'id' => 8,
                'sale_invoice_id' => 7,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 275.21,
                'iva_import' => 57.79,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 333.0,
                'obs' => 'pedido 333333',
                'created_at' => '2020-08-01 18:22:26',
                'updated_at' => '2020-08-01 18:22:26',
            ),
            8 => 
            array (
                'id' => 9,
                'sale_invoice_id' => 8,
                'product_id' => 6,
                'quantity' => 1,
                'neto_import' => 500.0,
                'iva_import' => 105.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 605.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:01:06',
                'updated_at' => '2020-08-01 22:01:06',
            ),
            9 => 
            array (
                'id' => 10,
                'sale_invoice_id' => 8,
                'product_id' => 1,
                'quantity' => 1,
                'neto_import' => 777.0,
                'iva_import' => 163.17,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 94017.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:01:06',
                'updated_at' => '2020-08-01 22:01:06',
            ),
            10 => 
            array (
                'id' => 11,
                'sale_invoice_id' => 8,
                'product_id' => 49,
                'quantity' => 1,
                'neto_import' => 4800.0,
                'iva_import' => 504.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 5304.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:01:06',
                'updated_at' => '2020-08-01 22:01:06',
            ),
            11 => 
            array (
                'id' => 12,
                'sale_invoice_id' => 8,
                'product_id' => 14,
                'quantity' => 1,
                'neto_import' => 1300.0,
                'iva_import' => 136.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 14365.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:01:06',
                'updated_at' => '2020-08-01 22:01:06',
            ),
            12 => 
            array (
                'id' => 13,
                'sale_invoice_id' => 9,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 165.29,
                'iva_import' => 34.71,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 200.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:21:36',
                'updated_at' => '2020-08-01 22:21:36',
            ),
            13 => 
            array (
                'id' => 14,
                'sale_invoice_id' => 10,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 165.29,
                'iva_import' => 34.71,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 200.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:26:29',
                'updated_at' => '2020-08-01 22:26:29',
            ),
            14 => 
            array (
                'id' => 15,
                'sale_invoice_id' => 11,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 82.64,
                'iva_import' => 17.36,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 100.0,
                'obs' => 'pr',
                'created_at' => '2020-08-01 22:28:53',
                'updated_at' => '2020-08-01 22:28:53',
            ),
            15 => 
            array (
                'id' => 16,
                'sale_invoice_id' => 12,
                'product_id' => 4,
                'quantity' => 1,
                'neto_import' => 1500.0,
                'iva_import' => 315.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 1815.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:34:30',
                'updated_at' => '2020-08-01 22:34:30',
            ),
            16 => 
            array (
                'id' => 17,
                'sale_invoice_id' => 12,
                'product_id' => 6,
                'quantity' => 1,
                'neto_import' => 500.0,
                'iva_import' => 105.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 605.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:34:30',
                'updated_at' => '2020-08-01 22:34:30',
            ),
            17 => 
            array (
                'id' => 18,
                'sale_invoice_id' => 12,
                'product_id' => 5,
                'quantity' => 1,
                'neto_import' => 400.0,
                'iva_import' => 42.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 442.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:34:30',
                'updated_at' => '2020-08-01 22:34:30',
            ),
            18 => 
            array (
                'id' => 19,
                'sale_invoice_id' => 12,
                'product_id' => 42,
                'quantity' => 1,
                'neto_import' => 4100.0,
                'iva_import' => 430.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 45305.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:34:30',
                'updated_at' => '2020-08-01 22:34:30',
            ),
            19 => 
            array (
                'id' => 20,
                'sale_invoice_id' => 13,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 165.29,
                'iva_import' => 34.71,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 200.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:36:25',
                'updated_at' => '2020-08-01 22:36:25',
            ),
            20 => 
            array (
                'id' => 21,
                'sale_invoice_id' => 14,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 82.64,
                'iva_import' => 17.36,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 100.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:37:54',
                'updated_at' => '2020-08-01 22:37:54',
            ),
            21 => 
            array (
                'id' => 22,
                'sale_invoice_id' => 15,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 82.64,
                'iva_import' => 17.36,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 100.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:38:40',
                'updated_at' => '2020-08-01 22:38:40',
            ),
            22 => 
            array (
                'id' => 23,
                'sale_invoice_id' => 16,
                'product_id' => 1,
                'quantity' => 1,
                'neto_import' => 777.0,
                'iva_import' => 163.17,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 94017.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:40:48',
                'updated_at' => '2020-08-01 22:40:48',
            ),
            23 => 
            array (
                'id' => 24,
                'sale_invoice_id' => 16,
                'product_id' => 56,
                'quantity' => 1,
                'neto_import' => 5500.0,
                'iva_import' => 1155.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 6655.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:40:48',
                'updated_at' => '2020-08-01 22:40:48',
            ),
            24 => 
            array (
                'id' => 25,
                'sale_invoice_id' => 16,
                'product_id' => 55,
                'quantity' => 1,
                'neto_import' => 5400.0,
                'iva_import' => 567.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 5967.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:40:48',
                'updated_at' => '2020-08-01 22:40:48',
            ),
            25 => 
            array (
                'id' => 26,
                'sale_invoice_id' => 16,
                'product_id' => 53,
                'quantity' => 1,
                'neto_import' => 5200.0,
                'iva_import' => 546.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 5746.0,
                'obs' => NULL,
                'created_at' => '2020-08-01 22:40:48',
                'updated_at' => '2020-08-01 22:40:48',
            ),
            26 => 
            array (
                'id' => 27,
                'sale_invoice_id' => 17,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 165.29,
                'iva_import' => 34.71,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 200.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:41:59',
                'updated_at' => '2020-08-01 22:41:59',
            ),
            27 => 
            array (
                'id' => 28,
                'sale_invoice_id' => 18,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 82.64,
                'iva_import' => 17.36,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 100.0,
                'obs' => 'Prueba',
                'created_at' => '2020-08-01 22:42:54',
                'updated_at' => '2020-08-01 22:42:54',
            ),
            28 => 
            array (
                'id' => 29,
                'sale_invoice_id' => 19,
                'product_id' => 43,
                'quantity' => 1,
                'neto_import' => 4200.0,
                'iva_import' => 882.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 5082.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:35:07',
                'updated_at' => '2020-08-02 18:35:07',
            ),
            29 => 
            array (
                'id' => 30,
                'sale_invoice_id' => 19,
                'product_id' => 8,
                'quantity' => 1,
                'neto_import' => 700.0,
                'iva_import' => 147.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 847.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:35:07',
                'updated_at' => '2020-08-02 18:35:07',
            ),
            30 => 
            array (
                'id' => 31,
                'sale_invoice_id' => 19,
                'product_id' => 71,
                'quantity' => 1,
                'neto_import' => 7000.0,
                'iva_import' => 735.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 7735.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:35:07',
                'updated_at' => '2020-08-02 18:35:07',
            ),
            31 => 
            array (
                'id' => 32,
                'sale_invoice_id' => 19,
                'product_id' => 54,
                'quantity' => 1,
                'neto_import' => 5300.0,
                'iva_import' => 556.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 58565.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:35:07',
                'updated_at' => '2020-08-02 18:35:07',
            ),
            32 => 
            array (
                'id' => 33,
                'sale_invoice_id' => 20,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 413.22,
                'iva_import' => 86.78,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 500.0,
                'obs' => 'Prueba2',
                'created_at' => '2020-08-02 18:35:47',
                'updated_at' => '2020-08-02 18:35:47',
            ),
            33 => 
            array (
                'id' => 34,
                'sale_invoice_id' => 21,
                'product_id' => 1,
                'quantity' => 1,
                'neto_import' => 777.0,
                'iva_import' => 163.17,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 94017.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:42:57',
                'updated_at' => '2020-08-02 18:42:57',
            ),
            34 => 
            array (
                'id' => 35,
                'sale_invoice_id' => 21,
                'product_id' => 42,
                'quantity' => 1,
                'neto_import' => 4100.0,
                'iva_import' => 861.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 4961.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:42:57',
                'updated_at' => '2020-08-02 18:42:57',
            ),
            35 => 
            array (
                'id' => 36,
                'sale_invoice_id' => 21,
                'product_id' => 30,
                'quantity' => 1,
                'neto_import' => 2900.0,
                'iva_import' => 304.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 32045.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:42:57',
                'updated_at' => '2020-08-02 18:42:57',
            ),
            36 => 
            array (
                'id' => 37,
                'sale_invoice_id' => 21,
                'product_id' => 6,
                'quantity' => 1,
                'neto_import' => 500.0,
                'iva_import' => 52.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 5525.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:42:57',
                'updated_at' => '2020-08-02 18:42:57',
            ),
            37 => 
            array (
                'id' => 38,
                'sale_invoice_id' => 22,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 413.22,
                'iva_import' => 86.78,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 500.0,
                'obs' => 'Prueba2',
                'created_at' => '2020-08-02 18:43:35',
                'updated_at' => '2020-08-02 18:43:35',
            ),
            38 => 
            array (
                'id' => 39,
                'sale_invoice_id' => 23,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 100.83,
                'iva_import' => 21.17,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 122.0,
                'obs' => 'Prueba2',
                'created_at' => '2020-08-02 18:44:23',
                'updated_at' => '2020-08-02 18:44:23',
            ),
            39 => 
            array (
                'id' => 40,
                'sale_invoice_id' => 24,
                'product_id' => 42,
                'quantity' => 1,
                'neto_import' => 4100.0,
                'iva_import' => 861.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 4961.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:50:29',
                'updated_at' => '2020-08-02 18:50:29',
            ),
            40 => 
            array (
                'id' => 41,
                'sale_invoice_id' => 24,
                'product_id' => 2,
                'quantity' => 1,
                'neto_import' => 100.0,
                'iva_import' => 21.0,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 121.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:50:29',
                'updated_at' => '2020-08-02 18:50:29',
            ),
            41 => 
            array (
                'id' => 42,
                'sale_invoice_id' => 24,
                'product_id' => 2,
                'quantity' => 1,
                'neto_import' => 100.0,
                'iva_import' => 10.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 1105.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:50:29',
                'updated_at' => '2020-08-02 18:50:29',
            ),
            42 => 
            array (
                'id' => 43,
                'sale_invoice_id' => 24,
                'product_id' => 46,
                'quantity' => 1,
                'neto_import' => 4500.0,
                'iva_import' => 472.5,
                'iva_id' => 5,
                'discount' => 0,
                'discount_import' => 0.0,
                'total' => 49725.0,
                'obs' => NULL,
                'created_at' => '2020-08-02 18:50:29',
                'updated_at' => '2020-08-02 18:50:29',
            ),
            43 => 
            array (
                'id' => 44,
                'sale_invoice_id' => 25,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 165.29,
                'iva_import' => 34.71,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 200.0,
                'obs' => 'Prueba2',
                'created_at' => '2020-08-02 18:51:53',
                'updated_at' => '2020-08-02 18:51:53',
            ),
            44 => 
            array (
                'id' => 45,
                'sale_invoice_id' => 26,
                'product_id' => NULL,
                'quantity' => NULL,
                'neto_import' => 165.29,
                'iva_import' => 34.71,
                'iva_id' => 5,
                'discount' => NULL,
                'discount_import' => NULL,
                'total' => 200.0,
                'obs' => 'Prueba2',
                'created_at' => '2020-08-02 18:52:20',
                'updated_at' => '2020-08-02 18:52:20',
            ),
        ));
        
        
    }
}